//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covid19Radar.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Covid19Radar.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string TextStopTheSpreadOfCOVID19 {
            get {
                return ResourceManager.GetString("TextStopTheSpreadOfCOVID19", resourceCulture);
            }
        }
        
        internal static string TextWeWillHelpAgenciesContact {
            get {
                return ResourceManager.GetString("TextWeWillHelpAgenciesContact", resourceCulture);
            }
        }
        
        internal static string TextToProtectThoseAroundYou {
            get {
                return ResourceManager.GetString("TextToProtectThoseAroundYou", resourceCulture);
            }
        }
        
        internal static string ButtonIWantToHelp {
            get {
                return ResourceManager.GetString("ButtonIWantToHelp", resourceCulture);
            }
        }
        
        internal static string TitleHowItWorks {
            get {
                return ResourceManager.GetString("TitleHowItWorks", resourceCulture);
            }
        }
        
        internal static string ButtonNext {
            get {
                return ResourceManager.GetString("ButtonNext", resourceCulture);
            }
        }
        
        internal static string TitleConsentByUserPage {
            get {
                return ResourceManager.GetString("TitleConsentByUserPage", resourceCulture);
            }
        }
        
        internal static string TextUserAgreement {
            get {
                return ResourceManager.GetString("TextUserAgreement", resourceCulture);
            }
        }
        
        internal static string TextContainsDescriptionOfConsent1 {
            get {
                return ResourceManager.GetString("TextContainsDescriptionOfConsent1", resourceCulture);
            }
        }
        
        internal static string TextContainsDescriptionOfConsent2 {
            get {
                return ResourceManager.GetString("TextContainsDescriptionOfConsent2", resourceCulture);
            }
        }
        
        internal static string ButtonAgreeAndProceed {
            get {
                return ResourceManager.GetString("ButtonAgreeAndProceed", resourceCulture);
            }
        }
        
        internal static string TextStep1Description {
            get {
                return ResourceManager.GetString("TextStep1Description", resourceCulture);
            }
        }
        
        internal static string TextStep1Title {
            get {
                return ResourceManager.GetString("TextStep1Title", resourceCulture);
            }
        }
        
        internal static string TextStep2Description {
            get {
                return ResourceManager.GetString("TextStep2Description", resourceCulture);
            }
        }
        
        internal static string TextStep2Title {
            get {
                return ResourceManager.GetString("TextStep2Title", resourceCulture);
            }
        }
        
        internal static string TextStep3Description {
            get {
                return ResourceManager.GetString("TextStep3Description", resourceCulture);
            }
        }
        
        internal static string TextStep3Title {
            get {
                return ResourceManager.GetString("TextStep3Title", resourceCulture);
            }
        }
        
        internal static string TextStep4Description {
            get {
                return ResourceManager.GetString("TextStep4Description", resourceCulture);
            }
        }
        
        internal static string TextStep4Title {
            get {
                return ResourceManager.GetString("TextStep4Title", resourceCulture);
            }
        }
        
        internal static string ButtonStart {
            get {
                return ResourceManager.GetString("ButtonStart", resourceCulture);
            }
        }
        
        internal static string TextCovid19Radar {
            get {
                return ResourceManager.GetString("TextCovid19Radar", resourceCulture);
            }
        }
        
        internal static string TextProtectingOurLovedOnes {
            get {
                return ResourceManager.GetString("TextProtectingOurLovedOnes", resourceCulture);
            }
        }
        
        internal static string TextBluetoothDescription {
            get {
                return ResourceManager.GetString("TextBluetoothDescription", resourceCulture);
            }
        }
        
        internal static string TextBluetoothTitle {
            get {
                return ResourceManager.GetString("TextBluetoothTitle", resourceCulture);
            }
        }
        
        internal static string TitleDeviceAccess {
            get {
                return ResourceManager.GetString("TitleDeviceAccess", resourceCulture);
            }
        }
        
        internal static string TitleAppDescription {
            get {
                return ResourceManager.GetString("TitleAppDescription", resourceCulture);
            }
        }
        
        internal static string TextHowToWorks {
            get {
                return ResourceManager.GetString("TextHowToWorks", resourceCulture);
            }
        }
        
        internal static string TextAppDescription {
            get {
                return ResourceManager.GetString("TextAppDescription", resourceCulture);
            }
        }
        
        internal static string ButtonRegister {
            get {
                return ResourceManager.GetString("ButtonRegister", resourceCulture);
            }
        }
        
        internal static string ButtonAgree {
            get {
                return ResourceManager.GetString("ButtonAgree", resourceCulture);
            }
        }
        
        internal static string TermsOfServiceTitle1 {
            get {
                return ResourceManager.GetString("TermsOfServiceTitle1", resourceCulture);
            }
        }
        
        internal static string TermsOfServiceDescription1 {
            get {
                return ResourceManager.GetString("TermsOfServiceDescription1", resourceCulture);
            }
        }
        
        internal static string TermsOfServiceTitle2 {
            get {
                return ResourceManager.GetString("TermsOfServiceTitle2", resourceCulture);
            }
        }
        
        internal static string TermsOfServiceDescription2 {
            get {
                return ResourceManager.GetString("TermsOfServiceDescription2", resourceCulture);
            }
        }
        
        internal static string TermsOfServiceTitle3 {
            get {
                return ResourceManager.GetString("TermsOfServiceTitle3", resourceCulture);
            }
        }
        
        internal static string TermsOfServiceDescription3 {
            get {
                return ResourceManager.GetString("TermsOfServiceDescription3", resourceCulture);
            }
        }
        
        internal static string TermsOfServiceTitle4 {
            get {
                return ResourceManager.GetString("TermsOfServiceTitle4", resourceCulture);
            }
        }
        
        internal static string TermsOfServiceDescription4 {
            get {
                return ResourceManager.GetString("TermsOfServiceDescription4", resourceCulture);
            }
        }
        
        internal static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        internal static string StatusSettingsMenu {
            get {
                return ResourceManager.GetString("StatusSettingsMenu", resourceCulture);
            }
        }
        
        internal static string ListOfContributorsMenu {
            get {
                return ResourceManager.GetString("ListOfContributorsMenu", resourceCulture);
            }
        }
        
        internal static string UpdateInformationMenu {
            get {
                return ResourceManager.GetString("UpdateInformationMenu", resourceCulture);
            }
        }
        
        internal static string ButtonHome {
            get {
                return ResourceManager.GetString("ButtonHome", resourceCulture);
            }
        }
        
        internal static string TextYoureReadyToGo {
            get {
                return ResourceManager.GetString("TextYoureReadyToGo", resourceCulture);
            }
        }
        
        internal static string TitleSetupCompleted {
            get {
                return ResourceManager.GetString("TitleSetupCompleted", resourceCulture);
            }
        }
        
        internal static string TextStatusSettingsDescription {
            get {
                return ResourceManager.GetString("TextStatusSettingsDescription", resourceCulture);
            }
        }
        
        internal static string TextStatusSettingsEnterNumber {
            get {
                return ResourceManager.GetString("TextStatusSettingsEnterNumber", resourceCulture);
            }
        }
        
        internal static string TextStatusSettingsSMSDescription {
            get {
                return ResourceManager.GetString("TextStatusSettingsSMSDescription", resourceCulture);
            }
        }
        
        internal static string TextStatusSettingsSMSInfo {
            get {
                return ResourceManager.GetString("TextStatusSettingsSMSInfo", resourceCulture);
            }
        }
        
        internal static string TextStatusSettingsSubtitle {
            get {
                return ResourceManager.GetString("TextStatusSettingsSubtitle", resourceCulture);
            }
        }
        
        internal static string TitleStatusSettings {
            get {
                return ResourceManager.GetString("TitleStatusSettings", resourceCulture);
            }
        }
        
        internal static string TextPhoneNumberPlaceholder {
            get {
                return ResourceManager.GetString("TextPhoneNumberPlaceholder", resourceCulture);
            }
        }
        
        internal static string DetectedBeaconListMenu {
            get {
                return ResourceManager.GetString("DetectedBeaconListMenu", resourceCulture);
            }
        }
        
        internal static string LicenseAgreementMenu {
            get {
                return ResourceManager.GetString("LicenseAgreementMenu", resourceCulture);
            }
        }
        
        internal static string OtpEnterText {
            get {
                return ResourceManager.GetString("OtpEnterText", resourceCulture);
            }
        }
        
        internal static string OtpTitle {
            get {
                return ResourceManager.GetString("OtpTitle", resourceCulture);
            }
        }
        
        internal static string ButtonVerify {
            get {
                return ResourceManager.GetString("ButtonVerify", resourceCulture);
            }
        }
        
        internal static string DidntGetTheCodeText {
            get {
                return ResourceManager.GetString("DidntGetTheCodeText", resourceCulture);
            }
        }
        
        internal static string ResendText {
            get {
                return ResourceManager.GetString("ResendText", resourceCulture);
            }
        }
    }
}
