//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covid19Radar.Resx {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Covid19Radar.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   COVID19Radar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Agree に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonAgree {
            get {
                return ResourceManager.GetString("ButtonAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Agree and Proceed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonAgreeAndProceed {
            get {
                return ResourceManager.GetString("ButtonAgreeAndProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I want to help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonIWantToHelp {
            get {
                return ResourceManager.GetString("ButtonIWantToHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonNext {
            get {
                return ResourceManager.GetString("ButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonRegister {
            get {
                return ResourceManager.GetString("ButtonRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonStart {
            get {
                return ResourceManager.GetString("ButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HOME に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List of Contributors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListOfContributorsMenu {
            get {
                return ResourceManager.GetString("ListOfContributorsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusSettingsMenu {
            get {
                return ResourceManager.GetString("StatusSettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Except as provided herein, the failure to exercise a right or to require performance of an obligation under this Terms shall not effect a party&apos;s ability to exercise such right or require such performance at any time thereafter nor shall be the waiver of a breach constitute a waiver of any subsequent breach に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TermsOfServiceDescription1 {
            get {
                return ResourceManager.GetString("TermsOfServiceDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   These Terms and Conditions may have been translated if We have made them available to You on our Service. You agree that the original English text shall prevail in the case of a dispute. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TermsOfServiceDescription2 {
            get {
                return ResourceManager.GetString("TermsOfServiceDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   We may terminate or suspend Your access immediately, without prior notice or liability, for any reason whatsoever, including without limitation if You breach these Terms and Conditions. Upon termination, Your right to use the Service will cease immediately. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TermsOfServiceDescription3 {
            get {
                return ResourceManager.GetString("TermsOfServiceDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The laws of the Country, excluding its conflicts of law rules, shall govern this Terms and Your use of the Service. Your use of the Application may also be subject to other local, state, national, or international laws. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TermsOfServiceDescription4 {
            get {
                return ResourceManager.GetString("TermsOfServiceDescription4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1. Waiver に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TermsOfServiceTitle1 {
            get {
                return ResourceManager.GetString("TermsOfServiceTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2. Translation Interpretation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TermsOfServiceTitle2 {
            get {
                return ResourceManager.GetString("TermsOfServiceTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3. Termination に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TermsOfServiceTitle3 {
            get {
                return ResourceManager.GetString("TermsOfServiceTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   4. Governing Law に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TermsOfServiceTitle4 {
            get {
                return ResourceManager.GetString("TermsOfServiceTitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   We use Bluetooth Low Energy (aka BLE) signals to determine if you are near another Covid19Radar user.This Proximity data is only data that recognizes terminals. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextAppDescription {
            get {
                return ResourceManager.GetString("TextAppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This app uses Bluetooth signals to determine if you are near another contact tracing app user. 
        ///Select &apos;Always Allow&apos; to set up Bluetooth. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextBluetoothDescription {
            get {
                return ResourceManager.GetString("TextBluetoothDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allow Bluetooth に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextBluetoothTitle {
            get {
                return ResourceManager.GetString("TextBluetoothTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   󰗠Contains a description of the consent sentence.Contains a description of the consent sentence.Contains a description of the consent sentence.Contains a description of the consent sentence. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextContainsDescriptionOfConsent1 {
            get {
                return ResourceManager.GetString("TextContainsDescriptionOfConsent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   󰗠Contains a description of the consent sentence.Contains a description of the consent sentence.Contains a description of the consent sentence.Contains a description of the consent sentence. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextContainsDescriptionOfConsent2 {
            get {
                return ResourceManager.GetString("TextContainsDescriptionOfConsent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   COVID19Radar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextCovid19Radar {
            get {
                return ResourceManager.GetString("TextCovid19Radar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   How to works に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextHowToWorks {
            get {
                return ResourceManager.GetString("TextHowToWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Protecting our loved ones from COVID19 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextProtectingOurLovedOnes {
            get {
                return ResourceManager.GetString("TextProtectingOurLovedOnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No need to input personal information. We are using unique ID, allocated to you when installing an app. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextStep1Description {
            get {
                return ResourceManager.GetString("TextStep1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Installing an App に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextStep1Title {
            get {
                return ResourceManager.GetString("TextStep1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A contact with another app user for longer than 30 min in total, within a radius closer than 2m on average is recorded as &quot;Close Contact&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextStep2Description {
            get {
                return ResourceManager.GetString("TextStep2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recording Close Contact に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextStep2Title {
            get {
                return ResourceManager.GetString("TextStep2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please manually change your status to &quot;Positive&quot; after verifying your phone number.&quot;Positive&quot; Workflow , Now coordination with related parties. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextStep3Description {
            get {
                return ResourceManager.GetString("TextStep3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you are diagnosed COVID19 positive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextStep3Title {
            get {
                return ResourceManager.GetString("TextStep3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bluetooth needs to be turned on to record close contact. Please go to the next page to turn it on. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextStep4Description {
            get {
                return ResourceManager.GetString("TextStep4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Requirements to use this app に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextStep4Title {
            get {
                return ResourceManager.GetString("TextStep4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help Stop the spread of COVID19 by turning Bluetooth on に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextStopTheSpreadOfCOVID19 {
            get {
                return ResourceManager.GetString("TextStopTheSpreadOfCOVID19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To protect those around you, Please share your data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextToProtectThoseAroundYou {
            get {
                return ResourceManager.GetString("TextToProtectThoseAroundYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User agreement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextUserAgreement {
            get {
                return ResourceManager.GetString("TextUserAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you had close contact with a COVID19 case, We will help agencies contact you to prevent the spread of infection, to provide guidance and care に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextWeWillHelpAgenciesContact {
            get {
                return ResourceManager.GetString("TextWeWillHelpAgenciesContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleAppDescription {
            get {
                return ResourceManager.GetString("TitleAppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Terms of Service に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleConsentByUserPage {
            get {
                return ResourceManager.GetString("TitleConsentByUserPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device Access に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleDeviceAccess {
            get {
                return ResourceManager.GetString("TitleDeviceAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   How it works に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleHowItWorks {
            get {
                return ResourceManager.GetString("TitleHowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdateInformationMenu {
            get {
                return ResourceManager.GetString("UpdateInformationMenu", resourceCulture);
            }
        }
    }
}
