//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covid19Radar.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Covid19Radar.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string TextStopTheSpreadOfCOVID19 {
            get {
                return ResourceManager.GetString("TextStopTheSpreadOfCOVID19", resourceCulture);
            }
        }
        
        internal static string TextWeWillHelpAgenciesContact {
            get {
                return ResourceManager.GetString("TextWeWillHelpAgenciesContact", resourceCulture);
            }
        }
        
        internal static string TextToProtectThoseAroundYou {
            get {
                return ResourceManager.GetString("TextToProtectThoseAroundYou", resourceCulture);
            }
        }
        
        internal static string ButtonIWantToHelp {
            get {
                return ResourceManager.GetString("ButtonIWantToHelp", resourceCulture);
            }
        }
        
        internal static string TitleAppDescription {
            get {
                return ResourceManager.GetString("TitleAppDescription", resourceCulture);
            }
        }
        
        internal static string TextHowToWorks {
            get {
                return ResourceManager.GetString("TextHowToWorks", resourceCulture);
            }
        }
        
        internal static string TextAppDescription {
            get {
                return ResourceManager.GetString("TextAppDescription", resourceCulture);
            }
        }
        
        internal static string ButtonRegister {
            get {
                return ResourceManager.GetString("ButtonRegister", resourceCulture);
            }
        }
        
        internal static string TitleConsentByUserPage {
            get {
                return ResourceManager.GetString("TitleConsentByUserPage", resourceCulture);
            }
        }
        
        internal static string TextUserAgreement {
            get {
                return ResourceManager.GetString("TextUserAgreement", resourceCulture);
            }
        }
        
        internal static string TextContainsDescriptionOfConsent1 {
            get {
                return ResourceManager.GetString("TextContainsDescriptionOfConsent1", resourceCulture);
            }
        }
        
        internal static string TextContainsDescriptionOfConsent2 {
            get {
                return ResourceManager.GetString("TextContainsDescriptionOfConsent2", resourceCulture);
            }
        }
        
        internal static string ButtonAgreeAndProceed {
            get {
                return ResourceManager.GetString("ButtonAgreeAndProceed", resourceCulture);
            }
        }
        
        internal static string ButtonAgree {
            get {
                return ResourceManager.GetString("ButtonAgree", resourceCulture);
            }
        }
        
        internal static string TermsOfServiceTitle1 {
            get {
                return ResourceManager.GetString("TermsOfServiceTitle1", resourceCulture);
            }
        }
        
        internal static string TermsOfServiceDescription1 {
            get {
                return ResourceManager.GetString("TermsOfServiceDescription1", resourceCulture);
            }
        }
        
        internal static string TermsOfServiceTitle2 {
            get {
                return ResourceManager.GetString("TermsOfServiceTitle2", resourceCulture);
            }
        }
        
        internal static string TermsOfServiceDescription2 {
            get {
                return ResourceManager.GetString("TermsOfServiceDescription2", resourceCulture);
            }
        }
        
        internal static string TermsOfServiceTitle3 {
            get {
                return ResourceManager.GetString("TermsOfServiceTitle3", resourceCulture);
            }
        }
        
        internal static string TermsOfServiceDescription3 {
            get {
                return ResourceManager.GetString("TermsOfServiceDescription3", resourceCulture);
            }
        }
        
        internal static string TermsOfServiceTitle4 {
            get {
                return ResourceManager.GetString("TermsOfServiceTitle4", resourceCulture);
            }
        }
        
        internal static string TermsOfServiceDescription4 {
            get {
                return ResourceManager.GetString("TermsOfServiceDescription4", resourceCulture);
            }
        }
    }
}
