// <auto-generated />
using System;
using NUnit.Framework;
using Xamarin.UITest;

namespace CovidRadar.UITestV2
{
    [TestFixture(Platform.Android)]
    [TestFixture(Platform.iOS)]
    public abstract class BaseTestFixture
    {
        protected IApp app => AppManager.App;
        protected bool OnAndroid => AppManager.Platform == Platform.Android;
        protected bool OniOS => AppManager.Platform == Platform.iOS;

        protected BaseTestFixture(Platform platform)
        {
            AppManager.Platform = platform;
        }

        [SetUp]
        public virtual void BeforeEachTest()
        {
            Console.WriteLine("BeforeEachTest");
        }


        [OneTimeSetUp]
        public virtual void OneTimeSetUp()
        {
            AppManager.ReStartApp();
        }

        [TearDown]
        public virtual void TearDown()
        {
            Console.WriteLine("OneTimeSetUp");
        }

    }
}
