name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

# NOTE: CI/PR triggers should be set in the Classic Editor

variables:
- group: app-settings-dev
- name: AppVersion
  value: '2.1.0'

jobs:
- job: build_ios
  pool:
    vmImage: 'macOS-11'
  variables:
  - group: ios-signing-development
  - template: templates/variables/ios-build-environment-variables.yml
  steps:
  - template: templates/build/ios-build-development-template.yml
