name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

# NOTE: CI/PR triggers should be set in the Classic Editor

variables:
- group: app-settings-prod
- name: AppVersion
  value: '2.1.0'

jobs:
- job: build_ios
  pool:
    vmImage: 'macOS-11'
  variables:
  - group: ios-signing-distribution
  - template: templates/variables/ios-build-environment-variables.yml
  steps:
  - template: templates/build/ios-build-appstore-template.yml

- job: build_android
  pool:
    vmImage: 'macOS-11'
  variables:
  - group: android-signing-prod
  - template: templates/variables/android-build-environment-variables.yml
  steps:
  - template: templates/build/android-build-store-template.yml
