name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
    - release/app
    - develop/app
    - feature/*
  paths:
    include:
    - Covid19Radar
    - Covid19Radar.sln
    - azure-pipelines/app

variables:
- group: app-settings-dev
- name: AppVersion
  value: '2.0.0'

jobs:
- job: build_ios
  pool:
    vmImage: 'macOS-11'
  variables:
  - group: ios-signing-development
  - template: templates/variables/ios-build-environment-variables.yml
  steps:
  - template: templates/build/ios-build-development-template.yml
    parameters:
      isDefineDebug: true

- job: build_android
  pool:
    vmImage: 'macOS-11'
  variables:
  - group: android-signing-dev
  - template: templates/variables/android-build-environment-variables.yml
  steps:
  - template: templates/build/android-build-development-template.yml
