name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
    - release/app
  paths:
    include:
    - Covid19Radar
    - Covid19Radar.sln
    - azure-pipelines/app

variables:
- group: app-settings-prod
- name: AppVersion
  value: '1.4.1'

jobs:
- job: build_ios
  pool:
    vmImage: 'macOS-11'
  variables:
  - group: ios-signing-distribution
  - template: templates/variables/ios-build-environment-variables.yml
  steps:
  - template: templates/build/ios-build-appstore-template.yml

- job: build_android
  pool:
    vmImage: 'macOS-11'
  variables:
  - group: android-signing-prod
  - template: templates/variables/android-build-environment-variables.yml
  steps:
  - template: templates/build/android-build-release-template.yml
