//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covid19Radar.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Covid19Radar.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   COVID-19Radar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Agree に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonAgree {
            get {
                return ResourceManager.GetString("ButtonAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Complete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonComplete {
            get {
                return ResourceManager.GetString("ButtonComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonEnable {
            get {
                return ResourceManager.GetString("ButtonEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonFailed {
            get {
                return ResourceManager.GetString("ButtonFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HOME に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonHome {
            get {
                return ResourceManager.GetString("ButtonHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonNext {
            get {
                return ResourceManager.GetString("ButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Agree に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonNotAgree {
            get {
                return ResourceManager.GetString("ButtonNotAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sharing positive information and anonymous notification to others に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonNotifyOtherPage {
            get {
                return ResourceManager.GetString("ButtonNotifyOtherPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NotNow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonNotNow {
            get {
                return ResourceManager.GetString("ButtonNotNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Submit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonPositiveSubmit {
            get {
                return ResourceManager.GetString("ButtonPositiveSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonReset {
            get {
                return ResourceManager.GetString("ButtonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Share に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonShare {
            get {
                return ResourceManager.GetString("ButtonShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonStart {
            get {
                return ResourceManager.GetString("ButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No need to input personal information. We are using unique ID, allocated to you when installing an app. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionPageTextStep1Description {
            get {
                return ResourceManager.GetString("DescriptionPageTextStep1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A contact with another app user for longer than 30 min in total, within a radius closer than 2m on average is recorded as &quot;Close Contact&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionPageTextStep2Description {
            get {
                return ResourceManager.GetString("DescriptionPageTextStep2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please manually change your status to &quot;Positive&quot; after verifying your phone number.&quot;Positive&quot; Workflow , Now coordination with related parties. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionPageTextStep3Description {
            get {
                return ResourceManager.GetString("DescriptionPageTextStep3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bluetooth/Exposure Notification needs to be turned on to record close contact. Please go to the next page to turn it on. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionPageTextStep4Description {
            get {
                return ResourceManager.GetString("DescriptionPageTextStep4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Installing an App に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionPageTitleTextStep1 {
            get {
                return ResourceManager.GetString("DescriptionPageTitleTextStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recording Close Contact に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionPageTitleTextStep2 {
            get {
                return ResourceManager.GetString("DescriptionPageTitleTextStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you are diagnosed COVID-19 positive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionPageTitleTextStep3 {
            get {
                return ResourceManager.GetString("DescriptionPageTitleTextStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Requirements to use this app に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionPageTitleTextStep4 {
            get {
                return ResourceManager.GetString("DescriptionPageTitleTextStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogButtonCancel {
            get {
                return ResourceManager.GetString("DialogButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please check your network connection. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogNetworkConnectionError {
            get {
                return ResourceManager.GetString("DialogNetworkConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No known exposures に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExposuresPageNoExposures {
            get {
                return ResourceManager.GetString("ExposuresPageNoExposures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You will be notified if you have been exposed to someone who reported a positive COVID-19 result. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExposuresPageNoExposuresInfo {
            get {
                return ResourceManager.GetString("ExposuresPageNoExposuresInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you received a positive diagnosis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HomePageSubtitle1 {
            get {
                return ResourceManager.GetString("HomePageSubtitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Share the App に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HomePageSubtitle2 {
            get {
                return ResourceManager.GetString("HomePageSubtitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HOME に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to turn on notifications? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InitSettingPageDialogExposureNotificationTitle {
            get {
                return ResourceManager.GetString("InitSettingPageDialogExposureNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allow Exposure Notification / Bluetooth に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InitSettingPageTextExposureNotification {
            get {
                return ResourceManager.GetString("InitSettingPageTextExposureNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This app uses Exposure Notification / Bluetooth signals to determine if you are near another contact tracing app user. 
        ///Select &apos;Always Allow&apos; to set up Bluetooth. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InitSettingPageTextExposureNotificationDescription {
            get {
                return ResourceManager.GetString("InitSettingPageTextExposureNotificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadingTextDeleting {
            get {
                return ResourceManager.GetString("LoadingTextDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enabling に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadingTextEnabling {
            get {
                return ResourceManager.GetString("LoadingTextEnabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Waiting for register に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadingTextRegistering {
            get {
                return ResourceManager.GetString("LoadingTextRegistering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exposures に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainExposures {
            get {
                return ResourceManager.GetString("MainExposures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manual に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainTutorial {
            get {
                return ResourceManager.GetString("MainTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the Diagnosis Identifier に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageCodePlaceholder {
            get {
                return ResourceManager.GetString("NotifyOtherPageCodePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://microsoft.com/ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOthersLearnMoreUrl {
            get {
                return ResourceManager.GetString("NotifyOthersLearnMoreUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Privacy Policy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PrivacyPolicyPageTitle {
            get {
                return ResourceManager.GetString("PrivacyPolicyPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You&apos;re ready to go に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SetupCompletedPageTextYoureReadyToGo {
            get {
                return ResourceManager.GetString("SetupCompletedPageTextYoureReadyToGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The test date helps the app know when you may have been contagious and notify the right people of potential exposure. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SharePositiveDiagDateText {
            get {
                return ResourceManager.GetString("SharePositiveDiagDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please try again later. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageDialogExceptionText {
            get {
                return ResourceManager.GetString("NotifyOtherPageDialogExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diagnosis Submitted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SharePositiveDiagnosisPageDiagSubmittedText {
            get {
                return ResourceManager.GetString("SharePositiveDiagnosisPageDiagSubmittedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide a Diagnosis Identifier に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SharePositiveDiagnosisPageDiagUidIsEmptyText {
            get {
                return ResourceManager.GetString("SharePositiveDiagnosisPageDiagUidIsEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diagnosis Identifier Required に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SharePositiveDiagnosisPageDiagUidIsEmptyTitle {
            get {
                return ResourceManager.GetString("SharePositiveDiagnosisPageDiagUidIsEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enable Exposure Notifications before submitting a diagnosis. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SharePositiveDiagnosisPageNotEnabledENDialogText {
            get {
                return ResourceManager.GetString("SharePositiveDiagnosisPageNotEnabledENDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exposure Notifications Disabled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SharePositiveDiagnosisPageNotEnabledENDialogTitle {
            get {
                return ResourceManager.GetString("SharePositiveDiagnosisPageNotEnabledENDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Submitting Diagnosis... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SharePositiveDiagnosisPageSubmittingDialog {
            get {
                return ResourceManager.GetString("SharePositiveDiagnosisPageSubmittingDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verifying Diagnosis... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SharePositiveDiagnosisPageVerifyDialog {
            get {
                return ResourceManager.GetString("SharePositiveDiagnosisPageVerifyDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your diagnosis cannot be verified at this time to be submitted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SharePositiveDiagnosisPageVerifyFailedDialogText {
            get {
                return ResourceManager.GetString("SharePositiveDiagnosisPageVerifyFailedDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verification Failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SharePositiveDiagnosisPageVerifyFailedDialogTitle {
            get {
                return ResourceManager.GetString("SharePositiveDiagnosisPageVerifyFailedDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only those who have been exposed will receive a notification. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SharePositiveEntryCodeText {
            get {
                return ResourceManager.GetString("SharePositiveEntryCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The unique test identifier that came with your COVID-19 test must be used to verify your positive test result. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SharePositiveEntryCodeText2 {
            get {
                return ResourceManager.GetString("SharePositiveEntryCodeText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Protecting our loved ones from COVID-19 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartTutorialPageTextProtectingOurLovedOnes {
            get {
                return ResourceManager.GetString("StartTutorialPageTextProtectingOurLovedOnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Share a Positive Diagnosis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitileSharePositiveDiagnosis {
            get {
                return ResourceManager.GetString("TitileSharePositiveDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitileUserStatusSettings {
            get {
                return ResourceManager.GetString("TitileUserStatusSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Terms of Service に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleConsentByUserPage {
            get {
                return ResourceManager.GetString("TitleConsentByUserPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contributors List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleContributorsPage {
            get {
                return ResourceManager.GetString("TitleContributorsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device Access に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleDeviceAccess {
            get {
                return ResourceManager.GetString("TitleDeviceAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   How it works に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleHowItWorks {
            get {
                return ResourceManager.GetString("TitleHowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   License Agreement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleLicenseAgreement {
            get {
                return ResourceManager.GetString("TitleLicenseAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set up Completed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleSetupCompleted {
            get {
                return ResourceManager.GetString("TitleSetupCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleUpdateInformation {
            get {
                return ResourceManager.GetString("TitleUpdateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://covid19radar.z11.web.core.windows.net/en/contributor.html に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UrlContributor {
            get {
                return ResourceManager.GetString("UrlContributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://covid19radar.z11.web.core.windows.net/en/privacypolicy.html に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UrlPrivacyPolicy {
            get {
                return ResourceManager.GetString("UrlPrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://covid19radar.z11.web.core.windows.net/en/update.html に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UrlUpdate {
            get {
                return ResourceManager.GetString("UrlUpdate", resourceCulture);
            }
        }
    }
}
