//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covid19Radar.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Covid19Radar.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Covid19Radar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Agree に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonAgree {
            get {
                return ResourceManager.GetString("ButtonAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Agree and Proceed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonAgreeAndProceed {
            get {
                return ResourceManager.GetString("ButtonAgreeAndProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonEnable {
            get {
                return ResourceManager.GetString("ButtonEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HOME に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonHome {
            get {
                return ResourceManager.GetString("ButtonHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I want to help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonIWantToHelp {
            get {
                return ResourceManager.GetString("ButtonIWantToHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonNext {
            get {
                return ResourceManager.GetString("ButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NotNow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonNotNow {
            get {
                return ResourceManager.GetString("ButtonNotNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Submit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonPositiveSubmit {
            get {
                return ResourceManager.GetString("ButtonPositiveSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Register に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonRegister {
            get {
                return ResourceManager.GetString("ButtonRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonStart {
            get {
                return ResourceManager.GetString("ButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verify に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonVerify {
            get {
                return ResourceManager.GetString("ButtonVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No need to input personal information. We are using unique ID, allocated to you when installing an app. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionPageTextStep1Description {
            get {
                return ResourceManager.GetString("DescriptionPageTextStep1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SampleText に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionPageTextStep1Description2 {
            get {
                return ResourceManager.GetString("DescriptionPageTextStep1Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A contact with another app user for longer than 30 min in total, within a radius closer than 2m on average is recorded as &quot;Close Contact&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionPageTextStep2Description {
            get {
                return ResourceManager.GetString("DescriptionPageTextStep2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SampleText に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionPageTextStep2Description2 {
            get {
                return ResourceManager.GetString("DescriptionPageTextStep2Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please manually change your status to &quot;Positive&quot; after verifying your phone number.&quot;Positive&quot; Workflow , Now coordination with related parties. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionPageTextStep3Description {
            get {
                return ResourceManager.GetString("DescriptionPageTextStep3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bluetooth/Exposure Notification needs to be turned on to record close contact. Please go to the next page to turn it on. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionPageTextStep4Description {
            get {
                return ResourceManager.GetString("DescriptionPageTextStep4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Installing an App に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionPageTitleTextStep1 {
            get {
                return ResourceManager.GetString("DescriptionPageTitleTextStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recording Close Contact に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionPageTitleTextStep2 {
            get {
                return ResourceManager.GetString("DescriptionPageTitleTextStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you are diagnosed COVID19 positive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionPageTitleTextStep3 {
            get {
                return ResourceManager.GetString("DescriptionPageTitleTextStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Requirements to use this app に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DescriptionPageTitleTextStep4 {
            get {
                return ResourceManager.GetString("DescriptionPageTitleTextStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detected Beacon List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DetectedBeaconListMenu {
            get {
                return ResourceManager.GetString("DetectedBeaconListMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Average Distance に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DetectedBeaconPageTextAvgDistance {
            get {
                return ResourceManager.GetString("DetectedBeaconPageTextAvgDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Count に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DetectedBeaconPageTextCount {
            get {
                return ResourceManager.GetString("DetectedBeaconPageTextCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ElapsedTime に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DetectedBeaconPageTextElapsedTime {
            get {
                return ResourceManager.GetString("DetectedBeaconPageTextElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DetectedBeaconPageTextId {
            get {
                return ResourceManager.GetString("DetectedBeaconPageTextId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LastTime に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DetectedBeaconPageTextLastTime {
            get {
                return ResourceManager.GetString("DetectedBeaconPageTextLastTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MajorNo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DetectedBeaconPageTextMajorNo {
            get {
                return ResourceManager.GetString("DetectedBeaconPageTextMajorNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MinorNo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DetectedBeaconPageTextMinorNo {
            get {
                return ResourceManager.GetString("DetectedBeaconPageTextMinorNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogButtonOk {
            get {
                return ResourceManager.GetString("DialogButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please check your network connection. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogNetworkConnectionError {
            get {
                return ResourceManager.GetString("DialogNetworkConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No known exposures に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExposuresPageNoExposures {
            get {
                return ResourceManager.GetString("ExposuresPageNoExposures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You will be notified if you have been exposed to someone who reported a positive COVID-19 result. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExposuresPageNoExposuresInfo {
            get {
                return ResourceManager.GetString("ExposuresPageNoExposuresInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Notification に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HomeEnableNotification {
            get {
                return ResourceManager.GetString("HomeEnableNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HOME に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Infomation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HomePageUpdateInfomation {
            get {
                return ResourceManager.GetString("HomePageUpdateInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List of Contributors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HomePageViewListOfContributorsMenu {
            get {
                return ResourceManager.GetString("HomePageViewListOfContributorsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HomePageViewStatusSettingsMenu {
            get {
                return ResourceManager.GetString("HomePageViewStatusSettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allow Exposure Notification / Bluetooth に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InitSettingPageTextExposureNotification {
            get {
                return ResourceManager.GetString("InitSettingPageTextExposureNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This app uses Exposure Notification / Bluetooth signals to determine if you are near another contact tracing app user. 
        ///Select &apos;Always Allow&apos; to set up Bluetooth. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InitSettingPageTextExposureNotificationDescription {
            get {
                return ResourceManager.GetString("InitSettingPageTextExposureNotificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Didn&apos;t get the code? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputSmsOTPPageDidntGetTheCodeText {
            get {
                return ResourceManager.GetString("InputSmsOTPPageDidntGetTheCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter the Code that was sent to 
        ///「{0}」 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputSmsOTPPageOtpEnterText {
            get {
                return ResourceManager.GetString("InputSmsOTPPageOtpEnterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resend に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputSmsOTPPageResendText {
            get {
                return ResourceManager.GetString("InputSmsOTPPageResendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contributors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainContributors {
            get {
                return ResourceManager.GetString("MainContributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exposures に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainExposures {
            get {
                return ResourceManager.GetString("MainExposures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainHome {
            get {
                return ResourceManager.GetString("MainHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   License に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainLicense {
            get {
                return ResourceManager.GetString("MainLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notify に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainNotifyOther {
            get {
                return ResourceManager.GetString("MainNotifyOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manual に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainTutorial {
            get {
                return ResourceManager.GetString("MainTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainUpdateInfo {
            get {
                return ResourceManager.GetString("MainUpdateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Share A Positive Diagnosis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NofityPageButtonSharePositive {
            get {
                return ResourceManager.GetString("NofityPageButtonSharePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Share A Positive Diagnosis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NofityPageShareDiag {
            get {
                return ResourceManager.GetString("NofityPageShareDiag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you tested positive for the virus that causes COVID-19, you can choose to share your diagnosis.  This will help others in your community contain the spread of the virus. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NofityPageShareYourCase {
            get {
                return ResourceManager.GetString("NofityPageShareYourCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the Diagnosis Identifier に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageCodePlaceholder {
            get {
                return ResourceManager.GetString("NotifyOtherPageCodePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you received a positive diagnosis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOtherPageTextStatusSettingsSubtitle {
            get {
                return ResourceManager.GetString("NotifyOtherPageTextStatusSettingsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://microsoft.com/ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyOthersLearnMoreUrl {
            get {
                return ResourceManager.GetString("NotifyOthersLearnMoreUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Learn more に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotifyPageLearnMore {
            get {
                return ResourceManager.GetString("NotifyPageLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You&apos;re ready to go に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SetupCompletedPageTextYoureReadyToGo {
            get {
                return ResourceManager.GetString("SetupCompletedPageTextYoureReadyToGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The test date helps the app know when you may have been contagious and notify the right people of potential exposure. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SharePositiveDiagDateText {
            get {
                return ResourceManager.GetString("SharePositiveDiagDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please try again later. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SharePositiveDiagnosisPageDiagExceptionText {
            get {
                return ResourceManager.GetString("SharePositiveDiagnosisPageDiagExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SharePositiveDiagnosisPageDiagExceptionTitle {
            get {
                return ResourceManager.GetString("SharePositiveDiagnosisPageDiagExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diagnosis Submitted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SharePositiveDiagnosisPageDiagSubmittedText {
            get {
                return ResourceManager.GetString("SharePositiveDiagnosisPageDiagSubmittedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Complete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SharePositiveDiagnosisPageDiagSubmittedTitle {
            get {
                return ResourceManager.GetString("SharePositiveDiagnosisPageDiagSubmittedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide a Diagnosis Identifier に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SharePositiveDiagnosisPageDiagUidIsEmptyText {
            get {
                return ResourceManager.GetString("SharePositiveDiagnosisPageDiagUidIsEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diagnosis Identifier Required に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SharePositiveDiagnosisPageDiagUidIsEmptyTitle {
            get {
                return ResourceManager.GetString("SharePositiveDiagnosisPageDiagUidIsEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SharePositiveDiagnosisPageDialogButton {
            get {
                return ResourceManager.GetString("SharePositiveDiagnosisPageDialogButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enable Exposure Notifications before submitting a diagnosis. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SharePositiveDiagnosisPageNotEnabledENDialogText {
            get {
                return ResourceManager.GetString("SharePositiveDiagnosisPageNotEnabledENDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exposure Notifications Disabled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SharePositiveDiagnosisPageNotEnabledENDialogTitle {
            get {
                return ResourceManager.GetString("SharePositiveDiagnosisPageNotEnabledENDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Submitting Diagnosis... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SharePositiveDiagnosisPageSubmittingDialog {
            get {
                return ResourceManager.GetString("SharePositiveDiagnosisPageSubmittingDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verifying Diagnosis... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SharePositiveDiagnosisPageVerifyDialog {
            get {
                return ResourceManager.GetString("SharePositiveDiagnosisPageVerifyDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your diagnosis cannot be verified at this time to be submitted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SharePositiveDiagnosisPageVerifyFailedDialogText {
            get {
                return ResourceManager.GetString("SharePositiveDiagnosisPageVerifyFailedDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verification Failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SharePositiveDiagnosisPageVerifyFailedDialogTitle {
            get {
                return ResourceManager.GetString("SharePositiveDiagnosisPageVerifyFailedDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only those who have been exposed will receive a notification. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SharePositiveEntryCodeText {
            get {
                return ResourceManager.GetString("SharePositiveEntryCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The unique test identifier that came with your COVID-19 test must be used to verify your positive test result. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SharePositiveEntryCodeText2 {
            get {
                return ResourceManager.GetString("SharePositiveEntryCodeText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verify and Share に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SharePositiveSubmitAndVerify {
            get {
                return ResourceManager.GetString("SharePositiveSubmitAndVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Protecting our loved ones from COVID19 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartTutorialPageTextProtectingOurLovedOnes {
            get {
                return ResourceManager.GetString("StartTutorialPageTextProtectingOurLovedOnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status Update Complete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusUpdateCompletePageTextStatusUpdateComplete {
            get {
                return ResourceManager.GetString("StatusUpdateCompletePageTextStatusUpdateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Share a Positive Diagnosis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitileSharePositiveDiagnosis {
            get {
                return ResourceManager.GetString("TitileSharePositiveDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitileUserStatusSettings {
            get {
                return ResourceManager.GetString("TitileUserStatusSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   App Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleAppDescription {
            get {
                return ResourceManager.GetString("TitleAppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Terms of Service に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleConsentByUserPage {
            get {
                return ResourceManager.GetString("TitleConsentByUserPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contributors List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleContributorsPage {
            get {
                return ResourceManager.GetString("TitleContributorsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detected Beacons に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleDetectedBeaconPage {
            get {
                return ResourceManager.GetString("TitleDetectedBeaconPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device Access に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleDeviceAccess {
            get {
                return ResourceManager.GetString("TitleDeviceAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exposures に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleExposures {
            get {
                return ResourceManager.GetString("TitleExposures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Heads up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleHeadsup {
            get {
                return ResourceManager.GetString("TitleHeadsup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   How it works に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleHowItWorks {
            get {
                return ResourceManager.GetString("TitleHowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   License Agreement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleLicenseAgreement {
            get {
                return ResourceManager.GetString("TitleLicenseAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter the Code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleOtp {
            get {
                return ResourceManager.GetString("TitleOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set up Completed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleSetupCompleted {
            get {
                return ResourceManager.GetString("TitleSetupCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status Update Complete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleStatusUpdateComplete {
            get {
                return ResourceManager.GetString("TitleStatusUpdateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleUpdateInformation {
            get {
                return ResourceManager.GetString("TitleUpdateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleUserSettings {
            get {
                return ResourceManager.GetString("TitleUserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://covid19radar.z11.web.core.windows.net/en/contributor.html に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UrlContributor {
            get {
                return ResourceManager.GetString("UrlContributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://covid19radar.z11.web.core.windows.net/en/qna.html に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UrlHeadsup {
            get {
                return ResourceManager.GetString("UrlHeadsup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://covid19radar.z11.web.core.windows.net/en/privacypolicy.html に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UrlPrivacyPolicy {
            get {
                return ResourceManager.GetString("UrlPrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://covid19radar.z11.web.core.windows.net/en/update.html に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UrlUpdate {
            get {
                return ResourceManager.GetString("UrlUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   090-1234-4567 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserSettingPageTextPhoneNumberPlaceholder {
            get {
                return ResourceManager.GetString("UserSettingPageTextPhoneNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you received a positive diagnosis, please enter your mobile number and update your status to protect your loved ones. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserSettingPageTextStatusSettingsDescription {
            get {
                return ResourceManager.GetString("UserSettingPageTextStatusSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter the mobile number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserSettingPageTextStatusSettingsEnterNumber {
            get {
                return ResourceManager.GetString("UserSettingPageTextStatusSettingsEnterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   We&apos;ll send you a verification code.
        ///Please check your SMS. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserSettingPageTextStatusSettingsSMSDescription {
            get {
                return ResourceManager.GetString("UserSettingPageTextStatusSettingsSMSDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   We will not store your phone number. It will be sent directly to the database of the government. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserSettingPageTextStatusSettingsSMSInfo {
            get {
                return ResourceManager.GetString("UserSettingPageTextStatusSettingsSMSInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you received a positive diagnosis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserSettingPageTextStatusSettingsSubtitle {
            get {
                return ResourceManager.GetString("UserSettingPageTextStatusSettingsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you received a positive diagnosis, please enter your mobile number and update your status to protect your loved ones. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserStatusPageTextStatusSettingsDescription {
            get {
                return ResourceManager.GetString("UserStatusPageTextStatusSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tap to change state に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserStatusPageTextStatusSettingsPickerTitle {
            get {
                return ResourceManager.GetString("UserStatusPageTextStatusSettingsPickerTitle", resourceCulture);
            }
        }
    }
}
