//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covid19Radar.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Covid19Radar.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ButtonAgree {
            get {
                return ResourceManager.GetString("ButtonAgree", resourceCulture);
            }
        }
        
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        public static string SettingsPageLicenseButton {
            get {
                return ResourceManager.GetString("SettingsPageLicenseButton", resourceCulture);
            }
        }
        
        public static string TitleLicenseAgreement {
            get {
                return ResourceManager.GetString("TitleLicenseAgreement", resourceCulture);
            }
        }
        
        public static string TitileUserStatusSettings {
            get {
                return ResourceManager.GetString("TitileUserStatusSettings", resourceCulture);
            }
        }
        
        public static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        public static string DialogNetworkConnectionError {
            get {
                return ResourceManager.GetString("DialogNetworkConnectionError", resourceCulture);
            }
        }
        
        public static string ButtonNotNow {
            get {
                return ResourceManager.GetString("ButtonNotNow", resourceCulture);
            }
        }
        
        public static string MainExposures {
            get {
                return ResourceManager.GetString("MainExposures", resourceCulture);
            }
        }
        
        public static string NotifyOthersLearnMoreUrl {
            get {
                return ResourceManager.GetString("NotifyOthersLearnMoreUrl", resourceCulture);
            }
        }
        
        public static string ExposuresPageExposureUnitPluralOnce {
            get {
                return ResourceManager.GetString("ExposuresPageExposureUnitPluralOnce", resourceCulture);
            }
        }
        
        public static string ExposuresPageExposureUnitPlural {
            get {
                return ResourceManager.GetString("ExposuresPageExposureUnitPlural", resourceCulture);
            }
        }
        
        public static string ExposuresPageNoExposures {
            get {
                return ResourceManager.GetString("ExposuresPageNoExposures", resourceCulture);
            }
        }
        
        public static string ExposuresPageNoExposuresInfo {
            get {
                return ResourceManager.GetString("ExposuresPageNoExposuresInfo", resourceCulture);
            }
        }
        
        public static string NotifyOtherPageDialogExceptionText {
            get {
                return ResourceManager.GetString("NotifyOtherPageDialogExceptionText", resourceCulture);
            }
        }
        
        public static string NotifyOtherPageDialogExceptionTitle {
            get {
                return ResourceManager.GetString("NotifyOtherPageDialogExceptionTitle", resourceCulture);
            }
        }
        
        public static string NotifyOtherPageDialogSubmittedTitle {
            get {
                return ResourceManager.GetString("NotifyOtherPageDialogSubmittedTitle", resourceCulture);
            }
        }
        
        public static string LoadingTextSubmittingDiagnosis {
            get {
                return ResourceManager.GetString("LoadingTextSubmittingDiagnosis", resourceCulture);
            }
        }
        
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        public static string ButtonReset {
            get {
                return ResourceManager.GetString("ButtonReset", resourceCulture);
            }
        }
        
        public static string ButtonRegister {
            get {
                return ResourceManager.GetString("ButtonRegister", resourceCulture);
            }
        }
        
        public static string LoadingTextDeleting {
            get {
                return ResourceManager.GetString("LoadingTextDeleting", resourceCulture);
            }
        }
        
        public static string HomePageHeader2Description {
            get {
                return ResourceManager.GetString("HomePageHeader2Description", resourceCulture);
            }
        }
        
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        public static string ButtonShare {
            get {
                return ResourceManager.GetString("ButtonShare", resourceCulture);
            }
        }
        
        public static string ButtonNotifyOtherPage {
            get {
                return ResourceManager.GetString("ButtonNotifyOtherPage", resourceCulture);
            }
        }
        
        public static string PrivacyPolicyPageTitle {
            get {
                return ResourceManager.GetString("PrivacyPolicyPageTitle", resourceCulture);
            }
        }
        
        public static string LoadingTextRegistering {
            get {
                return ResourceManager.GetString("LoadingTextRegistering", resourceCulture);
            }
        }
        
        public static string SettingsPageDialogResetText {
            get {
                return ResourceManager.GetString("SettingsPageDialogResetText", resourceCulture);
            }
        }
        
        public static string SettingsPageDialogResetTitle {
            get {
                return ResourceManager.GetString("SettingsPageDialogResetTitle", resourceCulture);
            }
        }
        
        public static string SettingsPageDialogResetCompletedTitle {
            get {
                return ResourceManager.GetString("SettingsPageDialogResetCompletedTitle", resourceCulture);
            }
        }
        
        public static string SettingsPageDialogResetCompletedText {
            get {
                return ResourceManager.GetString("SettingsPageDialogResetCompletedText", resourceCulture);
            }
        }
        
        public static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
        
        public static string SettingsPageReinitializeLabel {
            get {
                return ResourceManager.GetString("SettingsPageReinitializeLabel", resourceCulture);
            }
        }
        
        public static string SettingsPageReinitializeDescription {
            get {
                return ResourceManager.GetString("SettingsPageReinitializeDescription", resourceCulture);
            }
        }
        
        public static string ButtonReturnToRegistration {
            get {
                return ResourceManager.GetString("ButtonReturnToRegistration", resourceCulture);
            }
        }
        
        public static string PositiveRegistrationText {
            get {
                return ResourceManager.GetString("PositiveRegistrationText", resourceCulture);
            }
        }
        
        public static string PositiveRegistrationConfirmText {
            get {
                return ResourceManager.GetString("PositiveRegistrationConfirmText", resourceCulture);
            }
        }
        
        public static string HelpMenuPageTitle {
            get {
                return ResourceManager.GetString("HelpMenuPageTitle", resourceCulture);
            }
        }
        
        public static string HelpMenuPageMenu {
            get {
                return ResourceManager.GetString("HelpMenuPageMenu", resourceCulture);
            }
        }
        
        public static string HelpMenuPageLabel1 {
            get {
                return ResourceManager.GetString("HelpMenuPageLabel1", resourceCulture);
            }
        }
        
        public static string HelpMenuPageLabel2 {
            get {
                return ResourceManager.GetString("HelpMenuPageLabel2", resourceCulture);
            }
        }
        
        public static string HelpMenuPageLabel3 {
            get {
                return ResourceManager.GetString("HelpMenuPageLabel3", resourceCulture);
            }
        }
        
        public static string HelpMenuPageLabel4 {
            get {
                return ResourceManager.GetString("HelpMenuPageLabel4", resourceCulture);
            }
        }
        
        public static string HelpPage1Title {
            get {
                return ResourceManager.GetString("HelpPage1Title", resourceCulture);
            }
        }
        
        public static string HelpPage2Title {
            get {
                return ResourceManager.GetString("HelpPage2Title", resourceCulture);
            }
        }
        
        public static string HelpPage3Title {
            get {
                return ResourceManager.GetString("HelpPage3Title", resourceCulture);
            }
        }
        
        public static string HelpPage4Title {
            get {
                return ResourceManager.GetString("HelpPage4Title", resourceCulture);
            }
        }
        
        public static string HelpPage1Description1Text {
            get {
                return ResourceManager.GetString("HelpPage1Description1Text", resourceCulture);
            }
        }
        
        public static string HelpPage1Description2Title {
            get {
                return ResourceManager.GetString("HelpPage1Description2Title", resourceCulture);
            }
        }
        
        public static string HelpPage1Description2Text {
            get {
                return ResourceManager.GetString("HelpPage1Description2Text", resourceCulture);
            }
        }
        
        public static string HelpPage1Description3Title {
            get {
                return ResourceManager.GetString("HelpPage1Description3Title", resourceCulture);
            }
        }
        
        public static string HelpPage1Description3Text {
            get {
                return ResourceManager.GetString("HelpPage1Description3Text", resourceCulture);
            }
        }
        
        public static string HelpPage2Description1 {
            get {
                return ResourceManager.GetString("HelpPage2Description1", resourceCulture);
            }
        }
        
        public static string HelpPage2Description2 {
            get {
                return ResourceManager.GetString("HelpPage2Description2", resourceCulture);
            }
        }
        
        public static string HelpPage2Description3 {
            get {
                return ResourceManager.GetString("HelpPage2Description3", resourceCulture);
            }
        }
        
        public static string HelpPage2Label1 {
            get {
                return ResourceManager.GetString("HelpPage2Label1", resourceCulture);
            }
        }
        
        public static string HelpPage2Label2 {
            get {
                return ResourceManager.GetString("HelpPage2Label2", resourceCulture);
            }
        }
        
        public static string HelpPage2Label3 {
            get {
                return ResourceManager.GetString("HelpPage2Label3", resourceCulture);
            }
        }
        
        public static string HelpPage4ButtonText {
            get {
                return ResourceManager.GetString("HelpPage4ButtonText", resourceCulture);
            }
        }
        
        public static string HelpPage4Description1 {
            get {
                return ResourceManager.GetString("HelpPage4Description1", resourceCulture);
            }
        }
        
        public static string HelpPage4Description2 {
            get {
                return ResourceManager.GetString("HelpPage4Description2", resourceCulture);
            }
        }
        
        public static string HelpPage3Description1 {
            get {
                return ResourceManager.GetString("HelpPage3Description1", resourceCulture);
            }
        }
        
        public static string HelpPage3Description2 {
            get {
                return ResourceManager.GetString("HelpPage3Description2", resourceCulture);
            }
        }
        
        public static string HelpPage3Description3 {
            get {
                return ResourceManager.GetString("HelpPage3Description3", resourceCulture);
            }
        }
        
        public static string NotContactPageButtonText {
            get {
                return ResourceManager.GetString("NotContactPageButtonText", resourceCulture);
            }
        }
        
        public static string LowRiskContactPageLabel {
            get {
                return ResourceManager.GetString("LowRiskContactPageLabel", resourceCulture);
            }
        }
        
        public static string LowRiskContactPageCountSuffixHoursText {
            get {
                return ResourceManager.GetString("LowRiskContactPageCountSuffixHoursText", resourceCulture);
            }
        }
        
        public static string LowRiskContactPageCountSuffixMinutesText {
            get {
                return ResourceManager.GetString("LowRiskContactPageCountSuffixMinutesText", resourceCulture);
            }
        }
        
        public static string LowRiskContactPageDescription {
            get {
                return ResourceManager.GetString("LowRiskContactPageDescription", resourceCulture);
            }
        }
        
        public static string LowRiskContactPageHeaderTextPrefix {
            get {
                return ResourceManager.GetString("LowRiskContactPageHeaderTextPrefix", resourceCulture);
            }
        }
        
        public static string LowRiskContactPage_DailySummary_ScoreSum_Descritpion_Satisfied {
            get {
                return ResourceManager.GetString("LowRiskContactPage_DailySummary_ScoreSum_Descritpion_Satisfied", resourceCulture);
            }
        }
        
        public static string LowRiskContactPage_DailySummary_ScoreSum_Descritpion_Unsatisfied {
            get {
                return ResourceManager.GetString("LowRiskContactPage_DailySummary_ScoreSum_Descritpion_Unsatisfied", resourceCulture);
            }
        }
        
        public static string LowRiskContactPage_ExposureDuration_Description_Satisfied {
            get {
                return ResourceManager.GetString("LowRiskContactPage_ExposureDuration_Description_Satisfied", resourceCulture);
            }
        }
        
        public static string LowRiskContactPage_ExposureDuration_Description_Unsatisfied {
            get {
                return ResourceManager.GetString("LowRiskContactPage_ExposureDuration_Description_Unsatisfied", resourceCulture);
            }
        }
        
        public static string LowRiskContactPageAnnotationDecription {
            get {
                return ResourceManager.GetString("LowRiskContactPageAnnotationDecription", resourceCulture);
            }
        }
        
        public static string LowRiskContactPageAnnotationDecription2 {
            get {
                return ResourceManager.GetString("LowRiskContactPageAnnotationDecription2", resourceCulture);
            }
        }
        
        public static string NoRiskContactPageLabel {
            get {
                return ResourceManager.GetString("NoRiskContactPageLabel", resourceCulture);
            }
        }
        
        public static string NoRiskContactPageDescription {
            get {
                return ResourceManager.GetString("NoRiskContactPageDescription", resourceCulture);
            }
        }
        
        public static string NoRiskContactPageButtonText {
            get {
                return ResourceManager.GetString("NoRiskContactPageButtonText", resourceCulture);
            }
        }
        
        public static string ThankYouNotifyOtherPageLabel1 {
            get {
                return ResourceManager.GetString("ThankYouNotifyOtherPageLabel1", resourceCulture);
            }
        }
        
        public static string ThankYouNotifyOtherPageDescription1 {
            get {
                return ResourceManager.GetString("ThankYouNotifyOtherPageDescription1", resourceCulture);
            }
        }
        
        public static string TutorialPage3Title {
            get {
                return ResourceManager.GetString("TutorialPage3Title", resourceCulture);
            }
        }
        
        public static string TutorialPage3ButtonText {
            get {
                return ResourceManager.GetString("TutorialPage3ButtonText", resourceCulture);
            }
        }
        
        public static string TutorialPage6Label1 {
            get {
                return ResourceManager.GetString("TutorialPage6Label1", resourceCulture);
            }
        }
        
        public static string TutorialPage6ButtonText1 {
            get {
                return ResourceManager.GetString("TutorialPage6ButtonText1", resourceCulture);
            }
        }
        
        public static string TutorialPage6ButtonText2 {
            get {
                return ResourceManager.GetString("TutorialPage6ButtonText2", resourceCulture);
            }
        }
        
        public static string HelpPage1MainTitle {
            get {
                return ResourceManager.GetString("HelpPage1MainTitle", resourceCulture);
            }
        }
        
        public static string ContactedNotifyPageButton1 {
            get {
                return ResourceManager.GetString("ContactedNotifyPageButton1", resourceCulture);
            }
        }
        
        public static string ContactedNotifyPageMainText {
            get {
                return ResourceManager.GetString("ContactedNotifyPageMainText", resourceCulture);
            }
        }
        
        public static string ContactedNotifyPageTitle {
            get {
                return ResourceManager.GetString("ContactedNotifyPageTitle", resourceCulture);
            }
        }
        
        public static string InqueryPageTitle {
            get {
                return ResourceManager.GetString("InqueryPageTitle", resourceCulture);
            }
        }
        
        public static string InqueryPageTitle_Menu {
            get {
                return ResourceManager.GetString("InqueryPageTitle_Menu", resourceCulture);
            }
        }
        
        public static string HomePageDescription2 {
            get {
                return ResourceManager.GetString("HomePageDescription2", resourceCulture);
            }
        }
        
        public static string HomePageDescription3 {
            get {
                return ResourceManager.GetString("HomePageDescription3", resourceCulture);
            }
        }
        
        public static string HomePageDescription4 {
            get {
                return ResourceManager.GetString("HomePageDescription4", resourceCulture);
            }
        }
        
        public static string HomePageDescription5 {
            get {
                return ResourceManager.GetString("HomePageDescription5", resourceCulture);
            }
        }
        
        public static string ExposureCheckTitle {
            get {
                return ResourceManager.GetString("ExposureCheckTitle", resourceCulture);
            }
        }
        
        public static string HomePageTitle1 {
            get {
                return ResourceManager.GetString("HomePageTitle1", resourceCulture);
            }
        }
        
        public static string HomePageDialogExceptionTitle {
            get {
                return ResourceManager.GetString("HomePageDialogExceptionTitle", resourceCulture);
            }
        }
        
        public static string HomePageDialogExceptionDescription {
            get {
                return ResourceManager.GetString("HomePageDialogExceptionDescription", resourceCulture);
            }
        }
        
        public static string TermsofservicePageTitle {
            get {
                return ResourceManager.GetString("TermsofservicePageTitle", resourceCulture);
            }
        }
        
        public static string TutorialPage2Description1 {
            get {
                return ResourceManager.GetString("TutorialPage2Description1", resourceCulture);
            }
        }
        
        public static string TutorialPage2Description2 {
            get {
                return ResourceManager.GetString("TutorialPage2Description2", resourceCulture);
            }
        }
        
        public static string TutorialPage2Description3 {
            get {
                return ResourceManager.GetString("TutorialPage2Description3", resourceCulture);
            }
        }
        
        public static string TutorialPage2Description4 {
            get {
                return ResourceManager.GetString("TutorialPage2Description4", resourceCulture);
            }
        }
        
        public static string TutorialPage2Description5 {
            get {
                return ResourceManager.GetString("TutorialPage2Description5", resourceCulture);
            }
        }
        
        public static string TutorialPage2Title {
            get {
                return ResourceManager.GetString("TutorialPage2Title", resourceCulture);
            }
        }
        
        public static string TutorialPage5Description1 {
            get {
                return ResourceManager.GetString("TutorialPage5Description1", resourceCulture);
            }
        }
        
        public static string TutorialPage5Description2 {
            get {
                return ResourceManager.GetString("TutorialPage5Description2", resourceCulture);
            }
        }
        
        public static string TutorialPage5Description3 {
            get {
                return ResourceManager.GetString("TutorialPage5Description3", resourceCulture);
            }
        }
        
        public static string TutorialPage5Description4 {
            get {
                return ResourceManager.GetString("TutorialPage5Description4", resourceCulture);
            }
        }
        
        public static string TutorialPage5Title {
            get {
                return ResourceManager.GetString("TutorialPage5Title", resourceCulture);
            }
        }
        
        public static string MenuPageTitle {
            get {
                return ResourceManager.GetString("MenuPageTitle", resourceCulture);
            }
        }
        
        public static string NotifyOtherPageButton {
            get {
                return ResourceManager.GetString("NotifyOtherPageButton", resourceCulture);
            }
        }
        
        public static string NotifyOtherPageDescription3 {
            get {
                return ResourceManager.GetString("NotifyOtherPageDescription3", resourceCulture);
            }
        }
        
        public static string NotifyOtherPageDescription5 {
            get {
                return ResourceManager.GetString("NotifyOtherPageDescription5", resourceCulture);
            }
        }
        
        public static string NotifyOtherPageLabel {
            get {
                return ResourceManager.GetString("NotifyOtherPageLabel", resourceCulture);
            }
        }
        
        public static string NotifyOtherPageTitle {
            get {
                return ResourceManager.GetString("NotifyOtherPageTitle", resourceCulture);
            }
        }
        
        public static string TutorialPage1Button {
            get {
                return ResourceManager.GetString("TutorialPage1Button", resourceCulture);
            }
        }
        
        public static string TutorialPage1Description1 {
            get {
                return ResourceManager.GetString("TutorialPage1Description1", resourceCulture);
            }
        }
        
        public static string TutorialPage1Description2 {
            get {
                return ResourceManager.GetString("TutorialPage1Description2", resourceCulture);
            }
        }
        
        public static string TutorialPage1Description3 {
            get {
                return ResourceManager.GetString("TutorialPage1Description3", resourceCulture);
            }
        }
        
        public static string TutorialPage1Title1 {
            get {
                return ResourceManager.GetString("TutorialPage1Title1", resourceCulture);
            }
        }
        
        public static string TutorialPage1Title2 {
            get {
                return ResourceManager.GetString("TutorialPage1Title2", resourceCulture);
            }
        }
        
        public static string TutorialPage4Button1 {
            get {
                return ResourceManager.GetString("TutorialPage4Button1", resourceCulture);
            }
        }
        
        public static string TutorialPage4Button2 {
            get {
                return ResourceManager.GetString("TutorialPage4Button2", resourceCulture);
            }
        }
        
        public static string TutorialPage4Description {
            get {
                return ResourceManager.GetString("TutorialPage4Description", resourceCulture);
            }
        }
        
        public static string TutorialPage4Label {
            get {
                return ResourceManager.GetString("TutorialPage4Label", resourceCulture);
            }
        }
        
        public static string TutorialPage4Title1 {
            get {
                return ResourceManager.GetString("TutorialPage4Title1", resourceCulture);
            }
        }
        
        public static string TutorialPage4Title2 {
            get {
                return ResourceManager.GetString("TutorialPage4Title2", resourceCulture);
            }
        }
        
        public static string HomePageDescription0 {
            get {
                return ResourceManager.GetString("HomePageDescription0", resourceCulture);
            }
        }
        
        public static string NotifyOtherPageLabel2 {
            get {
                return ResourceManager.GetString("NotifyOtherPageLabel2", resourceCulture);
            }
        }
        
        public static string SubmitConsentPageButton {
            get {
                return ResourceManager.GetString("SubmitConsentPageButton", resourceCulture);
            }
        }
        
        public static string SubmitConsentPageTitle1 {
            get {
                return ResourceManager.GetString("SubmitConsentPageTitle1", resourceCulture);
            }
        }
        
        public static string SubmitConsentPageTitleDeepLink {
            get {
                return ResourceManager.GetString("SubmitConsentPageTitleDeepLink", resourceCulture);
            }
        }
        
        public static string ExposureNotificationServiceMessage4 {
            get {
                return ResourceManager.GetString("ExposureNotificationServiceMessage4", resourceCulture);
            }
        }
        
        public static string ExposuresPageTitle {
            get {
                return ResourceManager.GetString("ExposuresPageTitle", resourceCulture);
            }
        }
        
        public static string ExposuresPageLabel1 {
            get {
                return ResourceManager.GetString("ExposuresPageLabel1", resourceCulture);
            }
        }
        
        public static string UrlContactedPhone {
            get {
                return ResourceManager.GetString("UrlContactedPhone", resourceCulture);
            }
        }
        
        public static string LocalNotificationDescription {
            get {
                return ResourceManager.GetString("LocalNotificationDescription", resourceCulture);
            }
        }
        
        public static string LocalNotificationTitle {
            get {
                return ResourceManager.GetString("LocalNotificationTitle", resourceCulture);
            }
        }
        
        public static string LocalNotificationPermittedDescription {
            get {
                return ResourceManager.GetString("LocalNotificationPermittedDescription", resourceCulture);
            }
        }
        
        public static string LocalNotificationPermittedTitle {
            get {
                return ResourceManager.GetString("LocalNotificationPermittedTitle", resourceCulture);
            }
        }
        
        public static string InqueryPageDescription3 {
            get {
                return ResourceManager.GetString("InqueryPageDescription3", resourceCulture);
            }
        }
        
        public static string HomePagePastDays {
            get {
                return ResourceManager.GetString("HomePagePastDays", resourceCulture);
            }
        }
        
        public static string ExposureNotificationStatusMessageIsOptined {
            get {
                return ResourceManager.GetString("ExposureNotificationStatusMessageIsOptined", resourceCulture);
            }
        }
        
        public static string ExposureNotificationRestrictedTitle {
            get {
                return ResourceManager.GetString("ExposureNotificationRestrictedTitle", resourceCulture);
            }
        }
        
        public static string DialogNetworkConnectionErrorTitle {
            get {
                return ResourceManager.GetString("DialogNetworkConnectionErrorTitle", resourceCulture);
            }
        }
        
        public static string DialogExposureNotificationStartupErrorTitle {
            get {
                return ResourceManager.GetString("DialogExposureNotificationStartupErrorTitle", resourceCulture);
            }
        }
        
        public static string DialogExposureNotificationStartupError {
            get {
                return ResourceManager.GetString("DialogExposureNotificationStartupError", resourceCulture);
            }
        }
        
        public static string ExposureNotificationHandler1ErrorMessage {
            get {
                return ResourceManager.GetString("ExposureNotificationHandler1ErrorMessage", resourceCulture);
            }
        }
        
        public static string ExposureNotificationHandler2ErrorMessage {
            get {
                return ResourceManager.GetString("ExposureNotificationHandler2ErrorMessage", resourceCulture);
            }
        }
        
        public static string NotifyOther_Dialog_NoConnection {
            get {
                return ResourceManager.GetString("NotifyOther_Dialog_NoConnection", resourceCulture);
            }
        }
        
        public static string NotifyOtherPageDiag1Message {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiag1Message", resourceCulture);
            }
        }
        
        public static string NotifyOtherPageDiag1Title {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiag1Title", resourceCulture);
            }
        }
        
        public static string NotifyOtherPageDiag2Title {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiag2Title", resourceCulture);
            }
        }
        
        public static string NotifyOtherPageDiag3Message {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiag3Message", resourceCulture);
            }
        }
        
        public static string NotifyOtherPageDiag3Title {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiag3Title", resourceCulture);
            }
        }
        
        public static string NotifyOtherPageDiag4Message {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiag4Message", resourceCulture);
            }
        }
        
        public static string NotifyOtherPageDiag5Message {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiag5Message", resourceCulture);
            }
        }
        
        public static string NotifyOtherPageDiag6Message {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiag6Message", resourceCulture);
            }
        }
        
        public static string NotifyOtherPageDiag6Title {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiag6Title", resourceCulture);
            }
        }
        
        public static string NotifyOtherPageDiagReturnHomeTitle {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiagReturnHomeTitle", resourceCulture);
            }
        }
        
        public static string NotifyOtherPageDiagReturnHome {
            get {
                return ResourceManager.GetString("NotifyOtherPageDiagReturnHome", resourceCulture);
            }
        }
        
        public static string ProcessingNumberErrorDiagTitle {
            get {
                return ResourceManager.GetString("ProcessingNumberErrorDiagTitle", resourceCulture);
            }
        }
        
        public static string AppUtilsGetNewVersionDescription {
            get {
                return ResourceManager.GetString("AppUtilsGetNewVersionDescription", resourceCulture);
            }
        }
        
        public static string AppUtilsGetNewVersionTitle {
            get {
                return ResourceManager.GetString("AppUtilsGetNewVersionTitle", resourceCulture);
            }
        }
        
        public static string UrlVersion {
            get {
                return ResourceManager.GetString("UrlVersion", resourceCulture);
            }
        }
        
        public static string ExposureNotificationHandler3ErrorMessage {
            get {
                return ResourceManager.GetString("ExposureNotificationHandler3ErrorMessage", resourceCulture);
            }
        }
        
        public static string ContactedNotifyPageButton2 {
            get {
                return ResourceManager.GetString("ContactedNotifyPageButton2", resourceCulture);
            }
        }
        
        public static string ContactedNotifyPageDescription1 {
            get {
                return ResourceManager.GetString("ContactedNotifyPageDescription1", resourceCulture);
            }
        }
        
        public static string ContactedNotifyPageDescription1_1 {
            get {
                return ResourceManager.GetString("ContactedNotifyPageDescription1_1", resourceCulture);
            }
        }
        
        public static string ContactedNotifyPageDescription1_2 {
            get {
                return ResourceManager.GetString("ContactedNotifyPageDescription1_2", resourceCulture);
            }
        }
        
        public static string ContactedNotifyPageDescription1_3 {
            get {
                return ResourceManager.GetString("ContactedNotifyPageDescription1_3", resourceCulture);
            }
        }
        
        public static string ContactedNotifyPageDescription2 {
            get {
                return ResourceManager.GetString("ContactedNotifyPageDescription2", resourceCulture);
            }
        }
        
        public static string ContactedNotifyPageHighRiskActionAnnotationText {
            get {
                return ResourceManager.GetString("ContactedNotifyPageHighRiskActionAnnotationText", resourceCulture);
            }
        }
        
        public static string ReAgreeCheckButton {
            get {
                return ResourceManager.GetString("ReAgreeCheckButton", resourceCulture);
            }
        }
        
        public static string ReAgreePrivacyPolicyPageTitle {
            get {
                return ResourceManager.GetString("ReAgreePrivacyPolicyPageTitle", resourceCulture);
            }
        }
        
        public static string ReAgreePrivacyPolicyTextLink {
            get {
                return ResourceManager.GetString("ReAgreePrivacyPolicyTextLink", resourceCulture);
            }
        }
        
        public static string ReAgreeTermsOfServiceTextLink {
            get {
                return ResourceManager.GetString("ReAgreeTermsOfServiceTextLink", resourceCulture);
            }
        }
        
        public static string ReAgreeTermsOfServiceTitle {
            get {
                return ResourceManager.GetString("ReAgreeTermsOfServiceTitle", resourceCulture);
            }
        }
        
        public static string UrlTermsUpdate {
            get {
                return ResourceManager.GetString("UrlTermsUpdate", resourceCulture);
            }
        }
        
        public static string InqueryPageDescription2 {
            get {
                return ResourceManager.GetString("InqueryPageDescription2", resourceCulture);
            }
        }
        
        public static string InqueryPageButton1 {
            get {
                return ResourceManager.GetString("InqueryPageButton1", resourceCulture);
            }
        }
        
        public static string InqueryPageButton2 {
            get {
                return ResourceManager.GetString("InqueryPageButton2", resourceCulture);
            }
        }
        
        public static string InqueryPageButton3 {
            get {
                return ResourceManager.GetString("InqueryPageButton3", resourceCulture);
            }
        }
        
        public static string InqueryPageDescription1 {
            get {
                return ResourceManager.GetString("InqueryPageDescription1", resourceCulture);
            }
        }
        
        public static string SendLogConfirmationPageButton1 {
            get {
                return ResourceManager.GetString("SendLogConfirmationPageButton1", resourceCulture);
            }
        }
        
        public static string SendLogConfirmationPageDescription1 {
            get {
                return ResourceManager.GetString("SendLogConfirmationPageDescription1", resourceCulture);
            }
        }
        
        public static string SendLogConfirmationPageDescription2 {
            get {
                return ResourceManager.GetString("SendLogConfirmationPageDescription2", resourceCulture);
            }
        }
        
        public static string SendLogConfirmationPageDescription3 {
            get {
                return ResourceManager.GetString("SendLogConfirmationPageDescription3", resourceCulture);
            }
        }
        
        public static string SendLogConfirmationPageDescription4 {
            get {
                return ResourceManager.GetString("SendLogConfirmationPageDescription4", resourceCulture);
            }
        }
        
        public static string SendLogConfirmationPageDescription5 {
            get {
                return ResourceManager.GetString("SendLogConfirmationPageDescription5", resourceCulture);
            }
        }
        
        public static string SendLogConfirmationPageDescription6 {
            get {
                return ResourceManager.GetString("SendLogConfirmationPageDescription6", resourceCulture);
            }
        }
        
        public static string SendLogConfirmationPageDescription7 {
            get {
                return ResourceManager.GetString("SendLogConfirmationPageDescription7", resourceCulture);
            }
        }
        
        public static string SendLogConfirmationPageDescription8 {
            get {
                return ResourceManager.GetString("SendLogConfirmationPageDescription8", resourceCulture);
            }
        }
        
        public static string SendLogConfirmationPageTextLink1 {
            get {
                return ResourceManager.GetString("SendLogConfirmationPageTextLink1", resourceCulture);
            }
        }
        
        public static string SendLogConfirmationPageTitle {
            get {
                return ResourceManager.GetString("SendLogConfirmationPageTitle", resourceCulture);
            }
        }
        
        public static string SendLogCompletePageButton1 {
            get {
                return ResourceManager.GetString("SendLogCompletePageButton1", resourceCulture);
            }
        }
        
        public static string SendLogCompletePageButton2 {
            get {
                return ResourceManager.GetString("SendLogCompletePageButton2", resourceCulture);
            }
        }
        
        public static string SendLogCompletePageDescription1 {
            get {
                return ResourceManager.GetString("SendLogCompletePageDescription1", resourceCulture);
            }
        }
        
        public static string SendLogCompletePageDescription2 {
            get {
                return ResourceManager.GetString("SendLogCompletePageDescription2", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string FailedMessageToGetOperatingInformation {
            get {
                return ResourceManager.GetString("FailedMessageToGetOperatingInformation", resourceCulture);
            }
        }
        
        public static string FailedMessageToSaveOperatingInformation {
            get {
                return ResourceManager.GetString("FailedMessageToSaveOperatingInformation", resourceCulture);
            }
        }
        
        public static string FailedMessageToSendOperatingInformation {
            get {
                return ResourceManager.GetString("FailedMessageToSendOperatingInformation", resourceCulture);
            }
        }
        
        public static string InquiryMailBody {
            get {
                return ResourceManager.GetString("InquiryMailBody", resourceCulture);
            }
        }
        
        public static string InquiryMailSubject {
            get {
                return ResourceManager.GetString("InquiryMailSubject", resourceCulture);
            }
        }
        
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        public static string SendIdMailBody1 {
            get {
                return ResourceManager.GetString("SendIdMailBody1", resourceCulture);
            }
        }
        
        public static string SendIdMailBody2 {
            get {
                return ResourceManager.GetString("SendIdMailBody2", resourceCulture);
            }
        }
        
        public static string SendIdMailSubject {
            get {
                return ResourceManager.GetString("SendIdMailSubject", resourceCulture);
            }
        }
        
        public static string Sending {
            get {
                return ResourceManager.GetString("Sending", resourceCulture);
            }
        }
        
        public static string SendingError {
            get {
                return ResourceManager.GetString("SendingError", resourceCulture);
            }
        }
        
        public static string UrlContactedForm {
            get {
                return ResourceManager.GetString("UrlContactedForm", resourceCulture);
            }
        }
        
        public static string NotifyOtherPageDescription1 {
            get {
                return ResourceManager.GetString("NotifyOtherPageDescription1", resourceCulture);
            }
        }
        
        public static string NotifyOtherPageDescription2 {
            get {
                return ResourceManager.GetString("NotifyOtherPageDescription2", resourceCulture);
            }
        }
        
        public static string NotifyOtherPageDescription4 {
            get {
                return ResourceManager.GetString("NotifyOtherPageDescription4", resourceCulture);
            }
        }
        
        public static string NotifyOtherPageDescription6 {
            get {
                return ResourceManager.GetString("NotifyOtherPageDescription6", resourceCulture);
            }
        }
        
        public static string NotifyOtherPageNoSymptomsDescription1 {
            get {
                return ResourceManager.GetString("NotifyOtherPageNoSymptomsDescription1", resourceCulture);
            }
        }
        
        public static string NotifyOtherPageRadioButtonNo {
            get {
                return ResourceManager.GetString("NotifyOtherPageRadioButtonNo", resourceCulture);
            }
        }
        
        public static string NotifyOtherPageRadioButtonYes {
            get {
                return ResourceManager.GetString("NotifyOtherPageRadioButtonYes", resourceCulture);
            }
        }
        
        public static string NotifyOtherPageWithSymptomsDescription1 {
            get {
                return ResourceManager.GetString("NotifyOtherPageWithSymptomsDescription1", resourceCulture);
            }
        }
        
        public static string HelpPage3Description4 {
            get {
                return ResourceManager.GetString("HelpPage3Description4", resourceCulture);
            }
        }
        
        public static string HelpPage3Description5 {
            get {
                return ResourceManager.GetString("HelpPage3Description5", resourceCulture);
            }
        }
        
        public static string SubmitConsentPageDescription1_1 {
            get {
                return ResourceManager.GetString("SubmitConsentPageDescription1_1", resourceCulture);
            }
        }
        
        public static string SubmitConsentPageDescription1_2 {
            get {
                return ResourceManager.GetString("SubmitConsentPageDescription1_2", resourceCulture);
            }
        }
        
        public static string SubmitConsentPageDescription1_3 {
            get {
                return ResourceManager.GetString("SubmitConsentPageDescription1_3", resourceCulture);
            }
        }
        
        public static string SubmitConsentPageDescription1_4 {
            get {
                return ResourceManager.GetString("SubmitConsentPageDescription1_4", resourceCulture);
            }
        }
        
        public static string SubmitConsentPageDescription1_5 {
            get {
                return ResourceManager.GetString("SubmitConsentPageDescription1_5", resourceCulture);
            }
        }
        
        public static string SubmitConsentPageDescription1_6 {
            get {
                return ResourceManager.GetString("SubmitConsentPageDescription1_6", resourceCulture);
            }
        }
        
        public static string SubmitConsentPageDescription6 {
            get {
                return ResourceManager.GetString("SubmitConsentPageDescription6", resourceCulture);
            }
        }
        
        public static string SubmitConsentPageDescription7 {
            get {
                return ResourceManager.GetString("SubmitConsentPageDescription7", resourceCulture);
            }
        }
        
        public static string SubmitConsentPageDescription8 {
            get {
                return ResourceManager.GetString("SubmitConsentPageDescription8", resourceCulture);
            }
        }
        
        public static string SubmitConsentPageDescription9 {
            get {
                return ResourceManager.GetString("SubmitConsentPageDescription9", resourceCulture);
            }
        }
        
        public static string SubmitConsentPageDescription10 {
            get {
                return ResourceManager.GetString("SubmitConsentPageDescription10", resourceCulture);
            }
        }
        
        public static string HelpPage3Description6 {
            get {
                return ResourceManager.GetString("HelpPage3Description6", resourceCulture);
            }
        }
        
        public static string UrlPrivacyPolicy {
            get {
                return ResourceManager.GetString("UrlPrivacyPolicy", resourceCulture);
            }
        }
        
        public static string UrlTermOfUse {
            get {
                return ResourceManager.GetString("UrlTermOfUse", resourceCulture);
            }
        }
        
        public static string HowToReceiveProcessingNumberPageTitle {
            get {
                return ResourceManager.GetString("HowToReceiveProcessingNumberPageTitle", resourceCulture);
            }
        }
        
        public static string HowToReceiveProcessingNumberPageDescription1 {
            get {
                return ResourceManager.GetString("HowToReceiveProcessingNumberPageDescription1", resourceCulture);
            }
        }
        
        public static string HowToReceiveProcessingNumberPageDescription2 {
            get {
                return ResourceManager.GetString("HowToReceiveProcessingNumberPageDescription2", resourceCulture);
            }
        }
        
        public static string HowToReceiveProcessingNumberPageDescription3 {
            get {
                return ResourceManager.GetString("HowToReceiveProcessingNumberPageDescription3", resourceCulture);
            }
        }
        
        public static string HowToReceiveProcessingNumberPageDescription4 {
            get {
                return ResourceManager.GetString("HowToReceiveProcessingNumberPageDescription4", resourceCulture);
            }
        }
        
        public static string AndroidNotificationChannelName {
            get {
                return ResourceManager.GetString("AndroidNotificationChannelName", resourceCulture);
            }
        }
        
        public static string LocalExposureNotificationTitle {
            get {
                return ResourceManager.GetString("LocalExposureNotificationTitle", resourceCulture);
            }
        }
        
        public static string LocalExposureNotificationContent {
            get {
                return ResourceManager.GetString("LocalExposureNotificationContent", resourceCulture);
            }
        }
        
        public static string WebAccessibilityPolicyPageTitle {
            get {
                return ResourceManager.GetString("WebAccessibilityPolicyPageTitle", resourceCulture);
            }
        }
        
        public static string UrlWebAccessibilityPolicy {
            get {
                return ResourceManager.GetString("UrlWebAccessibilityPolicy", resourceCulture);
            }
        }
        
        public static string HomePageENStatusActiveTitle {
            get {
                return ResourceManager.GetString("HomePageENStatusActiveTitle", resourceCulture);
            }
        }
        
        public static string HomePageENStatusActiveDescription {
            get {
                return ResourceManager.GetString("HomePageENStatusActiveDescription", resourceCulture);
            }
        }
        
        public static string HomePageENStatusUnconfirmedTitle {
            get {
                return ResourceManager.GetString("HomePageENStatusUnconfirmedTitle", resourceCulture);
            }
        }
        
        public static string HomePageENStatusUnconfirmedDescription1 {
            get {
                return ResourceManager.GetString("HomePageENStatusUnconfirmedDescription1", resourceCulture);
            }
        }
        
        public static string HomePageENStatusUnconfirmedDescription2 {
            get {
                return ResourceManager.GetString("HomePageENStatusUnconfirmedDescription2", resourceCulture);
            }
        }
        
        public static string HomePageTroubleshootingButtonText {
            get {
                return ResourceManager.GetString("HomePageTroubleshootingButtonText", resourceCulture);
            }
        }
        
        public static string HomePageENStatusStoppedTitle {
            get {
                return ResourceManager.GetString("HomePageENStatusStoppedTitle", resourceCulture);
            }
        }
        
        public static string HomePageENStatusStoppedDescription1 {
            get {
                return ResourceManager.GetString("HomePageENStatusStoppedDescription1", resourceCulture);
            }
        }
        
        public static string HomePageENStatusStoppedDescription2 {
            get {
                return ResourceManager.GetString("HomePageENStatusStoppedDescription2", resourceCulture);
            }
        }
        
        public static string LatestConfirmationDateExplanationDialogText {
            get {
                return ResourceManager.GetString("LatestConfirmationDateExplanationDialogText", resourceCulture);
            }
        }
        
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        public static string HomePageQuestionIconAccessibilityTextiOS {
            get {
                return ResourceManager.GetString("HomePageQuestionIconAccessibilityTextiOS", resourceCulture);
            }
        }
        
        public static string HomePageQuestionIconAccessibilityTextAndroid {
            get {
                return ResourceManager.GetString("HomePageQuestionIconAccessibilityTextAndroid", resourceCulture);
            }
        }
        
        public static string InProgressText {
            get {
                return ResourceManager.GetString("InProgressText", resourceCulture);
            }
        }
        
        public static string DateTimeFormatToDisplayOnHomePage {
            get {
                return ResourceManager.GetString("DateTimeFormatToDisplayOnHomePage", resourceCulture);
            }
        }
        
        public static string ToSettingsButton {
            get {
                return ResourceManager.GetString("ToSettingsButton", resourceCulture);
            }
        }
        
        public static string CheckSettingsDialogTitle {
            get {
                return ResourceManager.GetString("CheckSettingsDialogTitle", resourceCulture);
            }
        }
        
        public static string ExposureNotificationOffWarningDialogMessage {
            get {
                return ResourceManager.GetString("ExposureNotificationOffWarningDialogMessage", resourceCulture);
            }
        }
        
        public static string BluetoothOffWarningDialogMessage {
            get {
                return ResourceManager.GetString("BluetoothOffWarningDialogMessage", resourceCulture);
            }
        }
        
        public static string LocationOffWarningDialogMessage {
            get {
                return ResourceManager.GetString("LocationOffWarningDialogMessage", resourceCulture);
            }
        }
        
        public static string TroubleshootingPageTitle {
            get {
                return ResourceManager.GetString("TroubleshootingPageTitle", resourceCulture);
            }
        }
        
        public static string TroubleshootingPageDescription1 {
            get {
                return ResourceManager.GetString("TroubleshootingPageDescription1", resourceCulture);
            }
        }
        
        public static string TroubleshootingPageDescription2 {
            get {
                return ResourceManager.GetString("TroubleshootingPageDescription2", resourceCulture);
            }
        }
        
        public static string TroubleshootingPageDescription3 {
            get {
                return ResourceManager.GetString("TroubleshootingPageDescription3", resourceCulture);
            }
        }
        
        public static string TroubleshootingPageDescription4 {
            get {
                return ResourceManager.GetString("TroubleshootingPageDescription4", resourceCulture);
            }
        }
        
        public static string TroubleshootingPageDescription5 {
            get {
                return ResourceManager.GetString("TroubleshootingPageDescription5", resourceCulture);
            }
        }
        
        public static string ProcessingNumberDescriptionDeepLink {
            get {
                return ResourceManager.GetString("ProcessingNumberDescriptionDeepLink", resourceCulture);
            }
        }
        
        public static string ProcessingNumberPlaceholderDeepLink {
            get {
                return ResourceManager.GetString("ProcessingNumberPlaceholderDeepLink", resourceCulture);
            }
        }
        
        public static string ConfirmAgreement {
            get {
                return ResourceManager.GetString("ConfirmAgreement", resourceCulture);
            }
        }
        
        public static string AgreeAndRegisterButton {
            get {
                return ResourceManager.GetString("AgreeAndRegisterButton", resourceCulture);
            }
        }
        
        public static string InquiryAboutRegistrationTitle {
            get {
                return ResourceManager.GetString("InquiryAboutRegistrationTitle", resourceCulture);
            }
        }
        
        public static string InquiryAboutRegistrationPhoneNumber {
            get {
                return ResourceManager.GetString("InquiryAboutRegistrationPhoneNumber", resourceCulture);
            }
        }
        
        public static string InquiryAboutRegistrationReceptionTime {
            get {
                return ResourceManager.GetString("InquiryAboutRegistrationReceptionTime", resourceCulture);
            }
        }
        
        public static string YourProcessingNumber {
            get {
                return ResourceManager.GetString("YourProcessingNumber", resourceCulture);
            }
        }
        
        public static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        public static string GpsAnnotationText {
            get {
                return ResourceManager.GetString("GpsAnnotationText", resourceCulture);
            }
        }
        
        public static string BluetoothAnnotationText {
            get {
                return ResourceManager.GetString("BluetoothAnnotationText", resourceCulture);
            }
        }
        
        public static string ScreenshotAnnotationText {
            get {
                return ResourceManager.GetString("ScreenshotAnnotationText", resourceCulture);
            }
        }
        
        public static string CocoaAnnotationText {
            get {
                return ResourceManager.GetString("CocoaAnnotationText", resourceCulture);
            }
        }
        
        public static string OsAnnotationText {
            get {
                return ResourceManager.GetString("OsAnnotationText", resourceCulture);
            }
        }
        
        public static string SmsAnnotationText {
            get {
                return ResourceManager.GetString("SmsAnnotationText", resourceCulture);
            }
        }
        
        public static string MyHerSysAnnotationText {
            get {
                return ResourceManager.GetString("MyHerSysAnnotationText", resourceCulture);
            }
        }
        
        public static string RandomCodeAnnotationText {
            get {
                return ResourceManager.GetString("RandomCodeAnnotationText", resourceCulture);
            }
        }
        
        public static string AnnotationSymbol {
            get {
                return ResourceManager.GetString("AnnotationSymbol", resourceCulture);
            }
        }
        
        public static string AnnotationSymbol1 {
            get {
                return ResourceManager.GetString("AnnotationSymbol1", resourceCulture);
            }
        }
        
        public static string AnnotationSymbol2 {
            get {
                return ResourceManager.GetString("AnnotationSymbol2", resourceCulture);
            }
        }
        
        public static string HomePageImageAnnotationText {
            get {
                return ResourceManager.GetString("HomePageImageAnnotationText", resourceCulture);
            }
        }
        
        public static string ContactedPageImageAnnotationText {
            get {
                return ResourceManager.GetString("ContactedPageImageAnnotationText", resourceCulture);
            }
        }
        
        public static string ContactedNotifyPageCountHeader {
            get {
                return ResourceManager.GetString("ContactedNotifyPageCountHeader", resourceCulture);
            }
        }
        
        public static string ContactedNotifyPageCountOneText {
            get {
                return ResourceManager.GetString("ContactedNotifyPageCountOneText", resourceCulture);
            }
        }
        
        public static string ContactedNotifyPageCountText {
            get {
                return ResourceManager.GetString("ContactedNotifyPageCountText", resourceCulture);
            }
        }
        
        public static string ContactedNotifyPageExposureDurationHeader {
            get {
                return ResourceManager.GetString("ContactedNotifyPageExposureDurationHeader", resourceCulture);
            }
        }
        
        public static string ContactedNotifyPageExposureDurationOne {
            get {
                return ResourceManager.GetString("ContactedNotifyPageExposureDurationOne", resourceCulture);
            }
        }
        
        public static string ContactedNotifyPageExposureDuration {
            get {
                return ResourceManager.GetString("ContactedNotifyPageExposureDuration", resourceCulture);
            }
        }
        
        public static string ExposurePageExposureDuration {
            get {
                return ResourceManager.GetString("ExposurePageExposureDuration", resourceCulture);
            }
        }
        
        public static string ThresholdTextOperatorGt {
            get {
                return ResourceManager.GetString("ThresholdTextOperatorGt", resourceCulture);
            }
        }
        
        public static string ThresholdTextOperatorLt {
            get {
                return ResourceManager.GetString("ThresholdTextOperatorLt", resourceCulture);
            }
        }
        
        public static string ThresholdTextOperatorGte {
            get {
                return ResourceManager.GetString("ThresholdTextOperatorGte", resourceCulture);
            }
        }
        
        public static string ThresholdTextOperatorLte {
            get {
                return ResourceManager.GetString("ThresholdTextOperatorLte", resourceCulture);
            }
        }
        
        public static string ThresholdTextOperatorEqual {
            get {
                return ResourceManager.GetString("ThresholdTextOperatorEqual", resourceCulture);
            }
        }
        
        public static string ExposuresPageToUtcDescription {
            get {
                return ResourceManager.GetString("ExposuresPageToUtcDescription", resourceCulture);
            }
        }
        
        public static string ExposuresPageFrom {
            get {
                return ResourceManager.GetString("ExposuresPageFrom", resourceCulture);
            }
        }
        
        public static string ExposuresPageTo {
            get {
                return ResourceManager.GetString("ExposuresPageTo", resourceCulture);
            }
        }
        
        public static string ExposureDateFormatDate {
            get {
                return ResourceManager.GetString("ExposureDateFormatDate", resourceCulture);
            }
        }
        
        public static string ExposureDateFormatMonth {
            get {
                return ResourceManager.GetString("ExposureDateFormatMonth", resourceCulture);
            }
        }
        
        public static string ExposureDateFormatYear {
            get {
                return ResourceManager.GetString("ExposureDateFormatYear", resourceCulture);
            }
        }
        
        public static string NotContactPageTitle {
            get {
                return ResourceManager.GetString("NotContactPageTitle", resourceCulture);
            }
        }
        
        public static string NotContactPageLabel1 {
            get {
                return ResourceManager.GetString("NotContactPageLabel1", resourceCulture);
            }
        }
        
        public static string NotContactPageDescription1 {
            get {
                return ResourceManager.GetString("NotContactPageDescription1", resourceCulture);
            }
        }
    }
}
